version: '3.8'

services:
  app:
    build: .
    container_name: minha-aplicacao
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=meubanco
      - DB_USER=root
      - DB_PASSWORD=senha123
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: meubanco
      MYSQL_ROOT_PASSWORD: senha123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
