openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Listar usu치rios
      responses:
        '200':
          description: Lista de usu치rios
    post:
      summary: Criar usu치rio
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Usu치rio criado com sucesso
